# \u5E94\u7528\u540D\u79F0
server:
  port: 8081
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://10.176.161.120:33066/hotnews_dev?characterEncoding=utf8&serverTimezone=GMT&useSSL=false&autoReconnect=true&rewriteBatchedStatements=true
    username: hotnews_dev
    password: 4g3yxxi0D3ZdMLz2JQSg3fnNK1ylp3us
  redis:
    cluster:
      nodes: 10.176.79.169:9736
    database: 0
    timeout: 10000ms
    lettuce:
      pool:
        max-active: 8
        max-wait: -1ms
        max-idle: 8
        min-idle: 0
  kafka:
    bootstrap-servers: dgdev-cold-backup-kafka.global.yyyhbx.kafka.oppo.dev:9095,dgdev-cold-backup-kafka.global.yyyjbx.kafka.oppo.dev:9095,dgdev-cold-backup-kafka.global.yyy4bx.kafka.oppo.dev:9095
    consumer:
      enable-auto-commit: true
      auto-commit-interval: 1000
      auto-offset-reset: latest
      client-id: 926f38ee-aafc-4064-8262-f360fd3331c7
      group-id: e547e0284f197403700aa5d97fc88b38
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer


logging:
  level:
    root: info

